server:
  port: 8002
spring:
  application:
    name: cloud-provider-payment #服务名称

# 数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbcloud?useUnicode=true&characterEncoding=utf-8&userSSL=true
    username: root
    password: 123456
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cl.springcloud.com.cl.springcloud.entities  #所有entity别名所在包

# 微服务客户端配置
eureka:
  instance:
    prefer-ip-address: true # 注册服务时使用服务ip地址
#    instance-id: cloud-provider-payment8002
  client:
    service-url:
      defaultZone: http://eureka-server7001:7001/eureka,http://eureka-server7002:7002/eureka

