spring:
  application:
    name: cloud-eureka-server7001
server:
  port: 7001
eureka:
  instance:
    hostname: eureka-server7001         # eureka实例主机名
  client:
    register-with-eureka: false      # 是否把自己注册到eureka中
    fetch-registry: false           # 是否从eureka 上获取服务的注册信息
    service-url:
      defaultZone: http://eureka-server7002:7002/eureka
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
