spring:
  application:
    name: cloud-consumer-eureka-order
server:
  port: 1100

# 微服务客户端配置
eureka:
  instance:
    prefer-ip-address: true # 注册服务时使用服务ip地址
  client:
    service-url:
#      defaultZone: http://eureka-server7001:7001/eureka,http://eureka-server7002:7002/eureka
      defaultZone: http://eureka-server7001:7001/eureka
